title: Junzhe Zhang's Homepage
page-top-title: Junzhe Zhang
top-section-bg-text: Welcome to my homepage
home-subtitle: Junzhe Zhang&ensp;|&ensp;East China Normal University
copyright-text: '&copy; Junzhe Zhang 2026. All Rights Reserved.'
